name: About Page Update

on:
  repository_dispatch:
    types: [Run flat.yaml from Google Sheets]
  workflow_dispatch: {}
  
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
          http_url: https://docs.google.com/spreadsheets/d/1DEdQ7Ote96pPL_ICYayJvd5nxunLqf3Q492i0AVRiuU/pub?gid=353377522&single=true&output=csv
          downloaded_filename: assets/data/about.csv 

      - name: Commit changes
        run: |
          git config --local user.name "Alissa Troiano"
          git config --local user.email "alissatroianonyc@gmail.com"
          git add assets/data/about.csv  # Specify the correct path
          git commit -m "Update about.csv from Google Sheets"
          git push origin master

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Assumes your site files are in the root directory
