name: Coaches Page

on:
  repository_dispatch:
    types: [Run flat.yaml from Google Sheets]
  workflow_dispatch: {}
  
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Fetch data
        uses: githubocto/flat@v2
        with:
          http_url: https://docs.google.com/spreadsheets/d/e/2PACX-1vRkAT9_7Fu1FnVRXDZswFm0KrZLQ8hJBGTRrPoT3gxjAMy6Zr0LWsKnbuOPnwwPghmCZ9QQv7NpKNi9/pub?gid=952790861&single=true&output=csv
          downloaded_filename: assets/data/data.csv

      - name: Commit changes
        run: |
          git config --local user.name "Alissa Troiano"
          git config --local user.email "alissatroianonyc@gmail.com"
          git add assets/data/data.csv
          git commit -m "Update data.csv from Google Sheets to edit coaches page"
          git push origin master

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Assumes your site files are in the root directory
